version: '3'
services:
    webstore:
        image: egapm/microsvcapp:webstore
        build:
            context: ../Modules/webstore/
            dockerfile:  $PWD/Modules/webstore/BTMEmbedded/Dockerfile
        container_name: webstore
        ports:
        - "8070:8080"
        networks:
        - testnet
        depends_on:
        - customer
        - product
        - order
        - quote
        - payment
    customer:
        image: egapm/microsvcapp:customers
        build:
            context: ../Modules/customers/
            dockerfile:  $PWD/Modules/customers/BTMEmbedded/Dockerfile 
        container_name: customer 
        networks:
        - testnet
        depends_on:
        - webstoredb 
    gateway:
        image: egapm/microsvcapp:gateway
        build:
            context: ../Modules/gateway/
            dockerfile:  $PWD/Modules/gateway/BTMEmbedded/Dockerfile 
        container_name: gateway 
        networks:
        - testnet
    order:
        image: egapm/microsvcapp:order
        build:
            context: ../Modules/order/
            dockerfile:  $PWD/Modules/order/BTMEmbedded/Dockerfile 
        container_name: order 
        networks:
        - testnet
        depends_on:
        - webstoredb 
    payment:
        image: egapm/microsvcapp:payment
        build:
            context: ../Modules/payment/
            dockerfile:  $PWD/Modules/payment/BTMEmbedded/Dockerfile 
        container_name: payment 
        networks:
        - testnet
        depends_on:
        - gateway 
    product:
        image: egapm/microsvcapp:product
        build:
            context: ../Modules/products/
            dockerfile:  $PWD/Modules/products/BTMEmbedded/Dockerfile 
        container_name: product 
        networks:
        - testnet
        depends_on:
        - webstoredb 
    quote:
        image: egapm/microsvcapp:quote
        build:
            context: ../Modules/quote/
            dockerfile:  $PWD/Modules/quote/BTMEmbedded/Dockerfile 
        container_name: quote 
        networks:
        - testnet
        depends_on:
        - webstoredb 
    webstoredb:
        image: egapm/new-webstore:mysql
        restart: always
        container_name: webstoredb 
        volumes:
        - ./Modules/mysqldb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        networks:
        - testnet

networks:
  testnet:

